In [2]:
#NumPy Library
import numpy as np

a = [9,3,3,5]
print(np.array(a))  # Converting list into numpy array


[9 3 3 5]


In [3]:
z = np.zeros((2, 3))
print(z)


[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
o = np.ones((3, 2))
print(o)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
r = np.arange(1, 10, 2)
print(r)


[1 3 5 7 9]


In [6]:

a = np.eye(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
b = np.eye(2, 4)
print(b)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [8]:
r = np.random.rand(5)
print(r)


[0.30511635 0.86871361 0.68561767 0.71476301 0.90717447]


In [9]:
r2 = np.random.rand(2, 3)
print(r2)


[[0.82731511 0.8135464  0.56042339]
 [0.81038778 0.89345973 0.48711768]]


In [10]:
x = np.random.randint(1, 10)
print(x)


6


In [11]:
arr = np.random.randint(10, 50, size=5)
print(arr)


[37 31 40 22 19]


In [12]:
mat = np.random.randint(1, 100, size=(2, 3))
print(mat)


[[ 5 43 34]
 [ 6  6 30]]
